export function getImageUrl(id) {
  return (
    "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/" +
    id.replace(/\s+/g, "") +
    "_0.jpg"
  );
}

export const tabIndexToCategory = {
  0: "All",
  1: "Top",
  2: "Jug",
  3: "Mid",
  4: "ADC",
  5: "Sup",
  6: "Free Rotation",
};

export const champions_data = [
  {
    id: "Aatrox",
    key: "266",
    name: "Aatrox",
    title: "the Darkin Blade",
    position: ["Top", "Mid"],
  },
  {
    id: "Ahri",
    key: "103",
    name: "Ahri",
    title: "the Nine-Tailed Fox",
    position: ["Mid"],
  },
  {
    id: "Akali",
    key: "84",
    name: "Akali",
    title: "the Rogue Assassin",
    position: ["Top", "Mid"],
  },
  {
    id: "Alistar",
    key: "12",
    name: "Alistar",
    title: "the Minotaur",
    position: ["Sup"],
  },
  {
    id: "Amumu",
    key: "32",
    name: "Amumu",
    title: "the Sad Mummy",
    position: ["Jug"],
  },
  {
    id: "Anivia",
    key: "34",
    name: "Anivia",
    title: "the Cryophoenix",
    position: ["Mid"],
  },
  {
    id: "Annie",
    key: "1",
    name: "Annie",
    title: "the Dark Child",
    position: ["Mid"],
  },
  {
    id: "Aphelios",
    key: "523",
    name: "Aphelios",
    title: "the Weapon of the Faithful",
    position: ["ADC"],
  },
  {
    id: "Ashe",
    key: "22",
    name: "Ashe",
    title: "the Frost Archer",
    position: ["ADC"],
  },
  {
    id: "AurelionSol",
    key: "136",
    name: "Aurelion Sol",
    title: "The Star Forger",
    position: ["Mid"],
  },
  {
    id: "Azir",
    name: "Azir",
    title: "the Emperor of the Sands",
    position: ["Mid"],
  },
  {
    id: "Bard",
    name: "Bard",
    title: "the Wandering Caretaker",
    position: ["Sup"],
  },
  {
    id: "Blitzcrank",
    name: "Blitzcrank",
    title: "the Great Steam Golem",
    position: ["Sup"],
  },
  {
    id: "Brand",
    name: "Brand",
    title: "the Burning Vengeance",
    position: ["Mid", "Sup"],
  },
  {
    id: "Braum",
    name: "Braum",
    title: "the Heart of the Freljord",
    position: ["Sup"],
  },
  {
    id: "Caitlyn",
    key: "51",
    name: "Caitlyn",
    title: "the Sheriff of Piltover",
    position: ["ADC"],
  },
  {
    id: "Camille",
    key: "164",
    name: "Camille",
    title: "the Steel Shadow",
    position: ["Top"],
  },
  {
    id: "Cassiopeia",
    key: "69",
    name: "Cassiopeia",
    title: "the Serpent's Embrace",
    position: ["Mid", "ADC"],
  },
  {
    id: "Chogath",
    key: "31",
    name: "Cho'Gath",
    title: "the Terror of the Void",
    position: ["Top"],
  },
  {
    id: "Corki",
    key: "42",
    name: "Corki",
    title: "the Daring Bombardier",
    position: ["Mid", "ADC"],
  },
  {
    id: "Darius",
    key: "122",
    name: "Darius",
    title: "the Hand of Noxus",
    position: ["Top"],
  },
  {
    id: "Diana",
    key: "131",
    name: "Diana",
    title: "Scorn of the Moon",
    position: ["Mid"],
  },
  {
    id: "Draven",
    key: "119",
    name: "Draven",
    title: "the Glorious Executioner",
    position: ["ADC"],
  },
  {
    id: "DrMundo",
    key: "36",
    name: "Dr. Mundo",
    title: "the Madman of Zaun",
    position: ["Top"],
  },
  {
    id: "Ekko",
    key: "245",
    name: "Ekko",
    title: "the Boy Who Shattered Time",
    position: ["Jug", "Mid"],
  },
  {
    id: "Elise",
    key: "60",
    name: "Elise",
    title: "the Spider Queen",
    position: ["Jug"],
  },
  {
    id: "Evelynn",
    key: "28",
    name: "Evelynn",
    title: "Agony's Embrace",
    position: ["Jug"],
  },
  {
    id: "Ezreal",
    key: "81",
    name: "Ezreal",
    title: "the Prodigal Explorer",
    position: ["ADC"],
  },
  {
    id: "Fiddlesticks",
    key: "9",
    name: "Fiddlesticks",
    title: "the Ancient Fear",
    position: ["Jug"],
  },
  {
    id: "Fiora",
    key: "114",
    name: "Fiora",
    title: "the Grand Duelist",
    position: ["Top"],
  },
  {
    id: "Fizz",
    key: "105",
    name: "Fizz",
    title: "the Tidal Trickster",
    position: ["Mid"],
  },
  {
    id: "Galio",
    key: "3",
    name: "Galio",
    title: "the Colossus",
    position: ["Mid"],
  },
  {
    id: "Gangplank",
    key: "41",
    name: "Gangplank",
    title: "the Saltwater Scourge",
    position: ["Top"],
  },
  {
    id: "Garen",
    key: "86",
    name: "Garen",
    title: "The Might of Demacia",
    position: ["Top"],
  },
  {
    id: "Gnar",
    key: "150",
    name: "Gnar",
    title: "the Missing Link",
    position: ["Top"],
  },
  {
    id: "Gragas",
    key: "79",
    name: "Gragas",
    title: "the Rabble Rouser",
    position: ["Jug"],
  },
  {
    id: "Graves",
    key: "104",
    name: "Graves",
    title: "the Outlaw",
    position: ["Jug"],
  },
  {
    id: "Hecarim",
    key: "120",
    name: "Hecarim",
    title: "the Shadow of War",
    position: ["Jug", "Top"],
  },
  {
    id: "Heimerdinger",
    key: "74",
    name: "Heimerdinger",
    title: "the Revered Inventor",
    position: ["Top"],
  },
  {
    id: "Illaoi",
    key: "420",
    name: "Illaoi",
    title: "the Kraken Priestess",
    position: ["Top"],
  },
  {
    id: "Irelia",
    key: "39",
    name: "Irelia",
    title: "the Blade Dancer",
    position: ["Top", "Mid"],
  },
  {
    id: "Ivern",
    key: "427",
    name: "Ivern",
    title: "the Green Father",
    position: ["Jug"],
  },
  {
    id: "Janna",
    key: "40",
    name: "Janna",
    title: "the Storm's Fury",
    position: ["Sup"],
  },
  {
    id: "JarvanIV",
    key: "59",
    name: "Jarvan IV",
    title: "the Exemplar of Demacia",
    position: ["Jug"],
  },
  {
    id: "Jax",
    key: "24",
    name: "Jax",
    title: "Grandmaster at Arms",
    position: ["Top"],
  },
  {
    id: "Jayce",
    key: "126",
    name: "Jayce",
    title: "the Defender of Tomorrow",
    position: ["Top", "Mid"],
  },
  {
    id: "Jhin",
    key: "202",
    name: "Jhin",
    title: "the Virtuoso",
    position: ["ADC"],
  },
  {
    id: "Jinx",
    key: "222",
    name: "Jinx",
    title: "the Loose Cannon",
    position: ["ADC"],
  },
  {
    id: "Kaisa",
    key: "145",
    name: "Kai'Sa",
    title: "Daughter of the Void",
    position: ["ADCTop"],
  },
  {
    id: "Kalista",
    key: "429",
    name: "Kalista",
    title: "the Spear of Vengeance",
    position: ["ADC", "Top"],
  },
  {
    id: "Karma",
    key: "43",
    name: "Karma",
    title: "the Enlightened One",
    position: ["Mid", "Sup"],
  },
  {
    id: "Karthus",
    key: "30",
    name: "Karthus",
    title: "the Deathsinger",
    position: ["Jug", "Mid"],
  },
  {
    id: "Kassadin",
    key: "38",
    name: "Kassadin",
    title: "the Void Walker",
    position: ["Mid"],
  },
  {
    id: "Katarina",
    key: "55",
    name: "Katarina",
    title: "the Sinister Blade",
    position: ["Mid"],
  },
  {
    id: "Kayle",
    key: "10",
    name: "Kayle",
    title: "the Righteous",
    position: ["Top"],
  },
  {
    id: "Kayn",
    key: "141",
    name: "Kayn",
    title: "the Shadow Reaper",
    position: ["Jug"],
  },
  {
    id: "Kennen",
    key: "85",
    name: "Kennen",
    title: "the Heart of the Tempest",
    position: ["Top"],
  },
  {
    id: "Khazix",
    key: "121",
    name: "Kha'Zix",
    title: "the Voidreaver",
    position: ["Jug"],
  },
  {
    id: "Kindred",
    key: "203",
    name: "Kindred",
    title: "The Eternal Hunters",
    position: ["Jug"],
  },
  {
    id: "Kled",
    key: "240",
    name: "Kled",
    title: "the Cantankerous Cavalier",
    position: ["Top"],
  },
  {
    id: "KogMaw",
    key: "96",
    name: "Kog'Maw",
    title: "the Mouth of the Abyss",
    position: ["ADC"],
  },
  {
    id: "Leblanc",
    key: "7",
    name: "LeBlanc",
    title: "the Deceiver",
    position: ["Mid"],
  },
  {
    id: "LeeSin",
    key: "64",
    name: "Lee Sin",
    title: "the Blind Monk",
    position: ["Jug"],
  },
  {
    id: "Leona",
    key: "89",
    name: "Leona",
    title: "the Radiant Dawn",
    position: ["Sup"],
  },
  {
    id: "Lissandra",
    key: "127",
    name: "Lissandra",
    title: "the Ice Witch",
    position: ["Mid"],
  },
  {
    id: "Lucian",
    key: "236",
    name: "Lucian",
    title: "the Purifier",
    position: ["Top", "Mid", "ADC"],
  },
  {
    id: "Lulu",
    key: "117",
    name: "Lulu",
    title: "the Fae Sorceress",
    position: ["Sup"],
  },
  {
    id: "Lux",
    key: "99",
    name: "Lux",
    title: "the Lady of Luminosity",
    position: ["Mid", "Sup"],
  },
  {
    id: "Malphite",
    key: "54",
    name: "Malphite",
    title: "Shard of the Monolith",
    position: ["Top"],
  },
  {
    id: "Malzahar",
    key: "90",
    name: "Malzahar",
    title: "the Prophet of the Void",
    position: ["Mid"],
  },
  {
    id: "Maokai",
    key: "57",
    name: "Maokai",
    title: "the Twisted Treant",
    position: ["Top"],
  },
  {
    id: "MasterYi",
    key: "11",
    name: "Master Yi",
    title: "the Wuju Bladesman",
    position: ["Jug"],
  },
  {
    id: "MissFortune",
    key: "21",
    name: "Miss Fortune",
    title: "the Bounty Hunter",
    position: ["ADC"],
  },
  {
    id: "MonkeyKing",
    key: "62",
    name: "Wukong",
    title: "the Monkey King",
    position: ["Top"],
  },
  {
    id: "Mordekaiser",
    key: "82",
    name: "Mordekaiser",
    title: "the Iron Revenant",
    position: ["Top"],
  },
  {
    id: "Morgana",
    key: "25",
    name: "Morgana",
    title: "the Fallen",
    position: ["Mid", "Sup"],
  },
  {
    id: "Nami",
    key: "267",
    name: "Nami",
    title: "the Tidecaller",
    position: ["Sup"],
  },
  {
    id: "Nasus",
    key: "75",
    name: "Nasus",
    title: "the Curator of the Sands",
    position: ["Top"],
  },
  {
    id: "Nautilus",
    key: "111",
    name: "Nautilus",
    title: "the Titan of the Depths",
    position: ["Sup"],
  },
  {
    id: "Neeko",
    key: "518",
    name: "Neeko",
    title: "the Curious Chameleon",
    position: ["Mid"],
  },
  {
    id: "Nidalee",
    key: "76",
    name: "Nidalee",
    title: "the Bestial Huntress",
    position: ["Jug"],
  },
  {
    id: "Nocturne",
    key: "56",
    name: "Nocturne",
    title: "the Eternal Nightmare",
    position: ["Jug"],
  },
  {
    id: "Nunu",
    key: "20",
    name: "Nunu & Willump",
    title: "the Boy and His Yeti",
    position: ["Jug"],
  },
  {
    id: "Olaf",
    key: "2",
    name: "Olaf",
    title: "the Berserker",
    position: ["Jug"],
  },
  {
    id: "Orianna",
    key: "61",
    name: "Orianna",
    title: "the Lady of Clockwork",
    position: ["Mid"],
  },
  {
    id: "Ornn",
    key: "516",
    name: "Ornn",
    title: "The Fire below the Mountain",
    position: ["Top"],
  },
  {
    id: "Pantheon",
    key: "80",
    name: "Pantheon",
    title: "the Unbreakable Spear",
    position: ["Mid"],
  },
  {
    id: "Poppy",
    key: "78",
    name: "Poppy",
    title: "Keeper of the Hammer",
    position: ["Top"],
  },
  {
    id: "Pyke",
    key: "555",
    name: "Pyke",
    title: "the Bloodharbor Ripper",
    position: ["Sup"],
  },
  {
    id: "Qiyana",
    key: "246",
    name: "Qiyana",
    title: "Empress of the Elements",
    position: ["Mid"],
  },
  {
    id: "Quinn",
    key: "133",
    name: "Quinn",
    title: "Demacia's Wings",
    position: ["Top"],
  },
  {
    id: "Rakan",
    key: "497",
    name: "Rakan",
    title: "The Charmer",
    position: ["Sup"],
  },
  {
    id: "Rammus",
    key: "33",
    name: "Rammus",
    title: "the Armordillo",
    position: ["Jug"],
  },
  {
    id: "RekSai",
    key: "421",
    name: "Rek'Sai",
    title: "the Void Burrower",
    position: ["Jug"],
  },
  {
    id: "Renekton",
    key: "58",
    name: "Renekton",
    title: "the Butcher of the Sands",
    position: ["Top"],
  },
  {
    id: "Rengar",
    key: "107",
    name: "Rengar",
    title: "the Pridestalker",
    position: ["Jug"],
  },
  {
    id: "Riven",
    key: "92",
    name: "Riven",
    title: "the Exile",
    position: ["Top"],
  },
  {
    id: "Rumble",
    key: "68",
    name: "Rumble",
    title: "the Mechanized Menace",
    position: ["Top", "Mid"],
  },
  {
    id: "Ryze",
    key: "13",
    name: "Ryze",
    title: "the Rune Mage",
    position: ["Mid"],
  },
  {
    id: "Sejuani",
    key: "113",
    name: "Sejuani",
    title: "Fury of the North",
    position: ["Jug"],
  },
  {
    id: "Senna",
    key: "235",
    name: "Senna",
    title: "the Redeemer",
    position: ["ADC", "Sup"],
  },
  {
    id: "Sett",
    key: "875",
    name: "Sett",
    title: "the Boss",
    position: ["Top", "Jug", "Sup"],
  },
  {
    id: "Shaco",
    key: "35",
    name: "Shaco",
    title: "the Demon Jester",
    position: ["Jug"],
  },
  {
    id: "Shen",
    key: "98",
    name: "Shen",
    title: "the Eye of Twilight",
    position: ["Top"],
  },
  {
    id: "Shyvana",
    key: "102",
    name: "Shyvana",
    title: "the Half-Dragon",
    position: ["Jug"],
  },
  {
    id: "Singed",
    key: "27",
    name: "Singed",
    title: "the Mad Chemist",
    position: ["Top"],
  },
  {
    id: "Sion",
    key: "14",
    name: "Sion",
    title: "The Undead Juggernaut",
    position: ["Top"],
  },
  {
    id: "Sivir",
    key: "15",
    name: "Sivir",
    title: "the Battle Mistress",
    position: ["ADC"],
  },
  {
    id: "Skarner",
    key: "72",
    name: "Skarner",
    title: "the Crystal Vanguard",
    position: ["Jug"],
  },
  {
    id: "Sona",
    key: "37",
    name: "Sona",
    title: "Maven of the Strings",
    position: ["Sup"],
  },
  {
    id: "Soraka",
    key: "16",
    name: "Soraka",
    title: "the Starchild",
    position: ["Sup"],
  },
  {
    id: "Swain",
    key: "50",
    name: "Swain",
    title: "the Noxian Grand General",
    position: ["Top", "Sup"],
  },
  {
    id: "Sylas",
    key: "517",
    name: "Sylas",
    title: "the Unshackled",
    position: ["Mid", "Top"],
  },
  {
    id: "Syndra",
    key: "134",
    name: "Syndra",
    title: "the Dark Sovereign",
    position: ["Mid"],
  },
  {
    id: "TahmKench",
    key: "223",
    name: "Tahm Kench",
    title: "the River King",
    position: ["Sup"],
  },
  {
    id: "Taliyah",
    key: "163",
    name: "Taliyah",
    title: "the Stoneweaver",
    position: ["Jug"],
  },
  {
    id: "Talon",
    key: "91",
    name: "Talon",
    title: "the Blade's Shadow",
    position: ["Mid"],
  },
  {
    id: "Taric",
    key: "44",
    name: "Taric",
    title: "the Shield of Valoran",
    position: ["Sup"],
  },
  {
    id: "Teemo",
    key: "17",
    name: "Teemo",
    title: "the Swift Scout",
    position: ["Top"],
  },
  {
    id: "Thresh",
    key: "412",
    name: "Thresh",
    title: "the Chain Warden",
    position: ["Sup"],
  },
  {
    id: "Tristana",
    key: "18",
    name: "Tristana",
    title: "the Yordle Gunner",
    position: ["ADC"],
  },
  {
    id: "Trundle",
    key: "48",
    name: "Trundle",
    title: "the Troll King",
    position: ["Jug"],
  },
  {
    id: "Tryndamere",
    key: "23",
    name: "Tryndamere",
    title: "the Barbarian King",
    position: ["Top"],
  },
  {
    id: "TwistedFate",
    key: "4",
    name: "Twisted Fate",
    title: "the Card Master",
    position: ["Mid"],
  },
  {
    id: "Twitch",
    key: "29",
    name: "Twitch",
    title: "the Plague Rat",
    position: ["ADC"],
  },
  {
    id: "Udyr",
    key: "77",
    name: "Udyr",
    title: "the Spirit Walker",
    position: ["Jug"],
  },
  {
    id: "Urgot",
    key: "6",
    name: "Urgot",
    title: "the Dreadnought",
    position: ["Top"],
  },
  {
    id: "Varus",
    key: "110",
    name: "Varus",
    title: "the Arrow of Retribution",
    position: ["ADC"],
  },
  {
    id: "Vayne",
    key: "67",
    name: "Vayne",
    title: "the Night Hunter",
    position: ["ADC"],
  },
  {
    id: "Veigar",
    key: "45",
    name: "Veigar",
    title: "the Tiny Master of Evil",
    position: ["Mid"],
  },
  {
    id: "Velkoz",
    key: "161",
    name: "Vel'Koz",
    title: "the Eye of the Void",
    position: ["Mid", "Sup"],
  },
  {
    id: "Vi",
    key: "254",
    name: "Vi",
    title: "the Piltover Enforcer",
    position: ["Jug"],
  },
  {
    id: "Viktor",
    key: "112",
    name: "Viktor",
    title: "the Machine Herald",
    position: ["Mid"],
  },
  {
    id: "Vladimir",
    key: "8",
    name: "Vladimir",
    title: "the Crimson Reaper",
    position: ["Top", "Mid"],
  },
  {
    id: "Volibear",
    key: "106",
    name: "Volibear",
    title: "the Thunder's Roar",
    position: ["Top", "Jug"],
  },
  {
    id: "Warwick",
    key: "19",
    name: "Warwick",
    title: "the Uncaged Wrath of Zaun",
    position: ["Jug"],
  },
  {
    id: "Xayah",
    key: "498",
    name: "Xayah",
    title: "the Rebel",
    position: ["ADC"],
  },
  {
    id: "Xerath",
    key: "101",
    name: "Xerath",
    title: "the Magus Ascendant",
    position: ["Mid", "Sup"],
  },
  {
    id: "XinZhao",
    key: "5",
    name: "Xin Zhao",
    title: "the Seneschal of Demacia",
    position: ["Jug"],
  },
  {
    id: "Yasuo",
    key: "157",
    name: "Yasuo",
    title: "the Unforgiven",
    position: ["Mid"],
  },
  {
    id: "Yorick",
    key: "83",
    name: "Yorick",
    title: "Shepherd of Souls",
    position: ["Top"],
  },
  {
    id: "Yuumi",
    key: "350",
    name: "Yuumi",
    title: "the Magical Cat",
    position: ["Sup"],
  },
  {
    id: "Zac",
    key: "154",
    name: "Zac",
    title: "the Secret Weapon",
    position: ["Jug"],
  },
  {
    id: "Zed",
    key: "238",
    name: "Zed",
    title: "the Master of Shadows",
    position: ["Mid"],
  },
  {
    id: "Ziggs",
    key: "115",
    name: "Ziggs",
    title: "the Hexplosives Expert",
    position: ["Mid"],
  },
  {
    id: "Zilean",
    key: "26",
    name: "Zilean",
    title: "the Chronokeeper",
    position: ["Mid", "Sup"],
  },
  {
    id: "Zoe",
    key: "142",
    name: "Zoe",
    title: "the Aspect of Twilight",
    position: ["Mid"],
  },
  {
    id: "Zyra",
    key: "143",
    name: "Zyra",
    title: "Rise of the Thorns",
    position: ["Mid", "Sup"],
  },
];
